language: java
branches:
  only:
    - develop
    - /^release-[0-999].[0-999]$/
    - master
notifications:
  email:
    recipients:
      - nelsonlz@outlook.com
addons:
  sonarcloud:
    organization: "nelson-lpz-soft"
    token:
      secure: $SONAR2 # encrypted value of your token


# services:
# - mysql
# - mongodb
# before_install:
# - mysql -e 'CREATE DATABASE IF NOT EXISTS forge;'
script:
  - mvn verify
  #Test unitario y de integracion con cobertura (jacoco)
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=nelson-lz_historypriceBE

  #SONARCLOUD
#  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=nelson-lpz-soft -Dsonar.login=$SONAR

#Deploy https://iwvg-ecosystem.herokuapp.com/api
#deploy:
#  provider: heroku
#  api_key:
#    secure: $HEROKU
#  on:
#    branch: master
#  app: historypricebe
  #, por defecto, nombre del artefacto
